name: Deploy to Production
# Trigger a deployment when master branch is updated.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Deployment Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g firebase-tools
      - env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_PRODUCTION_TOKEN }}
        run: firebase deploy --token $FIREBASE_TOKEN
